// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
#include "reg.h"
#include "noreg.h"
#include "compnoreg.h"
#include "compreg.h"
using namespace Rcpp;

RcppExport SEXP DPWeibull_noreg(SEXP burninSEXP, SEXP iterationSEXP, SEXP tlSEXP, SEXP trSEXP, SEXP deltaSEXP, SEXP piSEXP, SEXP cSEXP, SEXP nmSEXP, SEXP alphaSEXP, SEXP lambdaSEXP,SEXP lambda0SEXP, SEXP alpha00SEXP, SEXP alpha0SEXP, SEXP lambda00SEXP, SEXP alphaalphaSEXP, SEXP alphalambdaSEXP, SEXP nuSEXP, SEXP ngrpSEXP, SEXP aSEXP, SEXP bSEXP, SEXP ymaxSEXP, SEXP timeSEXP, SEXP mSEXP, SEXP thinSEXP) {

    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type iteration(iterationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tl(tlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tr(trSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pi(piSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nm(nmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda0(lambda0SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha00(alpha00SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< const double >::type lambda00(lambda00SEXP);
    Rcpp::traits::input_parameter< const double >::type alphaalpha(alphaalphaSEXP);
    Rcpp::traits::input_parameter< const double >::type alphalambda(alphalambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ngrp(ngrpSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< const int >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    __result = Rcpp::wrap(noreg(burnin, iteration, tl, tr, delta, pi, c, nm, alpha, lambda, lambda0, alpha00, alpha0, lambda00, alphaalpha, alphalambda, nu, ngrp, a, b, ymax, time,m,  thin));
    return __result;
}

RcppExport SEXP DPWeibull_noreg_resume(SEXP burninSEXP, SEXP iterationSEXP, SEXP tlSEXP, SEXP trSEXP, SEXP deltaSEXP, SEXP piSEXP, SEXP cSEXP, SEXP nmSEXP, SEXP alphaSEXP, SEXP lambdaSEXP,SEXP lambda0SEXP, SEXP alpha00SEXP, SEXP alpha0SEXP, SEXP lambda00SEXP, SEXP alphaalphaSEXP, SEXP alphalambdaSEXP, SEXP nuSEXP, SEXP ngrpSEXP, SEXP aSEXP, SEXP bSEXP, SEXP ymaxSEXP, SEXP timeSEXP, SEXP mSEXP, SEXP thinSEXP, SEXP emptybasketSEXP,SEXP allbasketsSEXP) {

    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type iteration(iterationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tl(tlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tr(trSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pi(piSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nm(nmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda0(lambda0SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha00(alpha00SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< const double >::type lambda00(lambda00SEXP);
    Rcpp::traits::input_parameter< const double >::type alphaalpha(alphaalphaSEXP);
    Rcpp::traits::input_parameter< const double >::type alphalambda(alphalambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ngrp(ngrpSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< const int >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter<std::vector<int> >::type emptybasket(emptybasketSEXP);
    Rcpp::traits::input_parameter<IntegerVector >::type allbaskets(allbasketsSEXP);
    __result = Rcpp::wrap(noreg_resume(burnin, iteration, tl, tr, delta, pi, c, nm, alpha, lambda, lambda0, alpha00, alpha0, lambda00, alphaalpha, alphalambda, nu, ngrp, a, b, ymax, time,m,  thin,emptybasket, allbaskets));
    return __result;
}

RcppExport SEXP DPWeibull_reg(SEXP burninSEXP, SEXP iterationSEXP, SEXP tlSEXP, SEXP trSEXP, SEXP deltaSEXP, SEXP piSEXP, SEXP xSEXP, SEXP cSEXP, SEXP nmSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP betaSEXP, SEXP lambda0SEXP, SEXP alpha00SEXP, SEXP alpha0SEXP, SEXP lambda00SEXP, SEXP alphaalphaSEXP, SEXP alphalambdaSEXP, SEXP nuSEXP, SEXP ngrpSEXP, SEXP aSEXP, SEXP bSEXP, SEXP ymaxSEXP, SEXP mSEXP, SEXP betaslSEXP, SEXP xplot1SEXP,SEXP xplot2SEXP, SEXP timeSEXP, SEXP thinSEXP) {

    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type iteration(iterationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tl(tlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tr(trSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pi(piSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nm(nmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda0(lambda0SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha00(alpha00SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< const double >::type lambda00(lambda00SEXP);
    Rcpp::traits::input_parameter< const double >::type alphaalpha(alphaalphaSEXP);
    Rcpp::traits::input_parameter< const double >::type alphalambda(alphalambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ngrp(ngrpSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type betasl(betaslSEXP);
    Rcpp::traits::input_parameter< NumericVector>::type xplot1(xplot1SEXP);
    Rcpp::traits::input_parameter< NumericVector>::type xplot2(xplot2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    __result = Rcpp::wrap(reg(burnin, iteration, tl, tr, delta, pi, x, c, nm, alpha, lambda, beta, lambda0, alpha00, alpha0, lambda00, alphaalpha, alphalambda, nu, ngrp, a, b, ymax, m, betasl, time, xplot1, xplot2, thin));
    return __result;
}

RcppExport SEXP DPWeibull_reg_resume(SEXP burninSEXP, SEXP iterationSEXP, SEXP tlSEXP, SEXP trSEXP, SEXP deltaSEXP, SEXP piSEXP, SEXP xSEXP, SEXP cSEXP, SEXP nmSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP betaSEXP, SEXP lambda0SEXP, SEXP alpha00SEXP, SEXP alpha0SEXP, SEXP lambda00SEXP, SEXP alphaalphaSEXP, SEXP alphalambdaSEXP, SEXP nuSEXP, SEXP ngrpSEXP, SEXP aSEXP, SEXP bSEXP, SEXP ymaxSEXP, SEXP mSEXP, SEXP betaslSEXP, SEXP xplot1SEXP,SEXP xplot2SEXP, SEXP timeSEXP, SEXP thinSEXP, SEXP emptybasketSEXP,SEXP allbasketsSEXP) {

    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type iteration(iterationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tl(tlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tr(trSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pi(piSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nm(nmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda0(lambda0SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha00(alpha00SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< const double >::type lambda00(lambda00SEXP);
    Rcpp::traits::input_parameter< const double >::type alphaalpha(alphaalphaSEXP);
    Rcpp::traits::input_parameter< const double >::type alphalambda(alphalambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ngrp(ngrpSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type betasl(betaslSEXP);
    Rcpp::traits::input_parameter< NumericVector>::type xplot1(xplot1SEXP);
    Rcpp::traits::input_parameter< NumericVector>::type xplot2(xplot2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter<std::vector<int> >::type emptybasket(emptybasketSEXP);
    Rcpp::traits::input_parameter<IntegerVector >::type allbaskets(allbasketsSEXP);
    __result = Rcpp::wrap(reg_resume(burnin, iteration, tl, tr, delta, pi, x, c, nm, alpha, lambda, beta, lambda0, alpha00, alpha0, lambda00, alphaalpha, alphalambda, nu, ngrp, a, b, ymax, m, betasl, time, xplot1, xplot2, thin,emptybasket, allbaskets));
    return __result;
}

RcppExport SEXP DPWeibull_compnoreg(SEXP burninSEXP, SEXP iterationSEXP, SEXP tSEXP, SEXP deltaSEXP, SEXP cSEXP, SEXP nmSEXP, SEXP alpha1SEXP, SEXP lambda1SEXP, SEXP lambda01SEXP, SEXP alpha2SEXP, SEXP lambda2SEXP, SEXP lambda02SEXP, SEXP pSEXP,SEXP alpha00SEXP, SEXP alpha0SEXP, SEXP lambda00SEXP, SEXP alphaalphaSEXP, SEXP alphalambdaSEXP,  SEXP gamma0SEXP, SEXP gamma1SEXP, SEXP nuSEXP, SEXP ngrpSEXP, SEXP aSEXP, SEXP bSEXP, SEXP ymaxSEXP, SEXP timeSEXP,SEXP mSEXP,  SEXP thinSEXP) {

    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type iteration(iterationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nm(nmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha1(alpha1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda01(lambda01SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda02(lambda02SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha00(alpha00SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< const double >::type lambda00(lambda00SEXP);
    Rcpp::traits::input_parameter< const double >::type alphaalpha(alphaalphaSEXP);
    Rcpp::traits::input_parameter< const double >::type alphalambda(alphalambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma0(gamma0SEXP);
    Rcpp::traits::input_parameter< const double >::type gamma1(gamma1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ngrp(ngrpSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    __result = Rcpp::wrap(compnoreg(burnin, iteration, t, delta, c, nm, alpha1, lambda1, lambda01, alpha2, lambda2, lambda02, p, alpha00, alpha0, lambda00, alphaalpha, alphalambda, gamma0, gamma1, nu, ngrp, a, b, ymax, time, m, thin));
    return __result;
}

RcppExport SEXP DPWeibull_compnoreg_resume(SEXP burninSEXP, SEXP iterationSEXP, SEXP tSEXP, SEXP deltaSEXP, SEXP cSEXP, SEXP nmSEXP, SEXP alpha1SEXP, SEXP lambda1SEXP, SEXP lambda01SEXP, SEXP alpha2SEXP, SEXP lambda2SEXP, SEXP lambda02SEXP, SEXP pSEXP,SEXP alpha00SEXP, SEXP alpha0SEXP, SEXP lambda00SEXP, SEXP alphaalphaSEXP, SEXP alphalambdaSEXP,  SEXP gamma0SEXP, SEXP gamma1SEXP, SEXP nuSEXP, SEXP ngrpSEXP, SEXP aSEXP, SEXP bSEXP, SEXP ymaxSEXP, SEXP timeSEXP,SEXP mSEXP,  SEXP thinSEXP, SEXP emptybasketSEXP,SEXP allbasketsSEXP) {

    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type iteration(iterationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nm(nmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha1(alpha1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda01(lambda01SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda02(lambda02SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha00(alpha00SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< const double >::type lambda00(lambda00SEXP);
    Rcpp::traits::input_parameter< const double >::type alphaalpha(alphaalphaSEXP);
    Rcpp::traits::input_parameter< const double >::type alphalambda(alphalambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma0(gamma0SEXP);
    Rcpp::traits::input_parameter< const double >::type gamma1(gamma1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ngrp(ngrpSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter<std::vector<int> >::type emptybasket(emptybasketSEXP);
    Rcpp::traits::input_parameter<IntegerVector >::type allbaskets(allbasketsSEXP);
    __result = Rcpp::wrap(compnoreg_resume(burnin, iteration, t, delta, c, nm, alpha1, lambda1, lambda01, alpha2, lambda2, lambda02, p, alpha00, alpha0, lambda00, alphaalpha, alphalambda, gamma0, gamma1, nu, ngrp, a, b, ymax, time, m, thin,emptybasket, allbaskets));
    return __result;
}

RcppExport SEXP DPWeibull_compreg(SEXP burninSEXP, SEXP iterationSEXP, SEXP tSEXP, SEXP xSEXP, SEXP deltaSEXP, SEXP cSEXP, SEXP nmSEXP, SEXP alpha1SEXP, SEXP lambda1SEXP, SEXP lambda01SEXP, SEXP alpha2SEXP, SEXP lambda2SEXP, SEXP lambda02SEXP, SEXP pSEXP,SEXP beta1SEXP,SEXP beta2SEXP,SEXP alpha00SEXP, SEXP alpha0SEXP, SEXP lambda00SEXP, SEXP alphaalphaSEXP, SEXP alphalambdaSEXP,  SEXP gamma0SEXP, SEXP gamma1SEXP, SEXP betaslSEXP,SEXP nuSEXP, SEXP ngrpSEXP, SEXP aSEXP, SEXP bSEXP, SEXP ymaxSEXP, SEXP timeSEXP,SEXP mSEXP,  SEXP thinSEXP, SEXP xplot1SEXP, SEXP xplot2SEXP) {

    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type iteration(iterationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nm(nmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha1(alpha1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda01(lambda01SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda02(lambda02SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha00(alpha00SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< const double >::type lambda00(lambda00SEXP);
    Rcpp::traits::input_parameter< const double >::type alphaalpha(alphaalphaSEXP);
    Rcpp::traits::input_parameter< const double >::type alphalambda(alphalambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma0(gamma0SEXP);
    Rcpp::traits::input_parameter< const double >::type gamma1(gamma1SEXP);
    Rcpp::traits::input_parameter< const double >::type betasl(betaslSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ngrp(ngrpSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xplot1(xplot1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xplot2(xplot2SEXP);
    __result = Rcpp::wrap(compreg(burnin, iteration, t, delta, x, c, nm, alpha1, lambda1, lambda01, alpha2, lambda2, lambda02, beta1, beta2, p, alpha00, alpha0, lambda00, alphaalpha, alphalambda, gamma0, gamma1, nu, ngrp, a, b, ymax, time, m, thin, betasl, xplot1, xplot2));
    return __result;
}

RcppExport SEXP DPWeibull_compreg_resume(SEXP burninSEXP, SEXP iterationSEXP, SEXP tSEXP, SEXP xSEXP, SEXP deltaSEXP, SEXP cSEXP, SEXP nmSEXP, SEXP alpha1SEXP, SEXP lambda1SEXP, SEXP lambda01SEXP, SEXP alpha2SEXP, SEXP lambda2SEXP, SEXP lambda02SEXP, SEXP pSEXP,SEXP beta1SEXP,SEXP beta2SEXP,SEXP alpha00SEXP, SEXP alpha0SEXP, SEXP lambda00SEXP, SEXP alphaalphaSEXP, SEXP alphalambdaSEXP,  SEXP gamma0SEXP, SEXP gamma1SEXP, SEXP betaslSEXP,SEXP nuSEXP, SEXP ngrpSEXP, SEXP aSEXP, SEXP bSEXP, SEXP ymaxSEXP, SEXP timeSEXP,SEXP mSEXP,  SEXP thinSEXP, SEXP xplot1SEXP, SEXP xplot2SEXP, SEXP emptybasketSEXP,SEXP allbasketsSEXP) {

    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type iteration(iterationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nm(nmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha1(alpha1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda01(lambda01SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda02(lambda02SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha00(alpha00SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< const double >::type lambda00(lambda00SEXP);
    Rcpp::traits::input_parameter< const double >::type alphaalpha(alphaalphaSEXP);
    Rcpp::traits::input_parameter< const double >::type alphalambda(alphalambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma0(gamma0SEXP);
    Rcpp::traits::input_parameter< const double >::type gamma1(gamma1SEXP);
    Rcpp::traits::input_parameter< const double >::type betasl(betaslSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ngrp(ngrpSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xplot1(xplot1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xplot2(xplot2SEXP);
    Rcpp::traits::input_parameter<std::vector<int> >::type emptybasket(emptybasketSEXP);
    Rcpp::traits::input_parameter<IntegerVector >::type allbaskets(allbasketsSEXP);
    __result = Rcpp::wrap(compreg_resume(burnin, iteration, t, delta, x, c, nm, alpha1, lambda1, lambda01, alpha2, lambda2, lambda02, beta1, beta2, p, alpha00, alpha0, lambda00, alphaalpha, alphalambda, gamma0, gamma1, nu, ngrp, a, b, ymax, time, m, thin, betasl, xplot1, xplot2, emptybasket, allbaskets));
    return __result;
}

RcppExport SEXP DPWeibull_predcompreg(SEXP alpharec1SEXP,SEXP lambdarec1SEXP,SEXP betarec1SEXP,
       SEXP alpharec2SEXP, SEXP lambdarec2SEXP,SEXP betarec2SEXP,SEXP precSEXP, SEXP xplotSEXP, SEXP tplotSEXP, SEXP alphaSEXP) {
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type tplot(tplotSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xplot(xplotSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type alpharec1(alpharec1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lambdarec1(lambdarec1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type betarec1(betarec1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type alpharec2(alpharec2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lambdarec2(lambdarec2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type betarec2(betarec2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type prec(precSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    __result = Rcpp::wrap(predcompreg(alpharec1,lambdarec1,betarec1,alpharec2,lambdarec2,betarec2,prec,xplot,tplot,alpha));
    return __result;
}

RcppExport SEXP DPWeibull_predreg(SEXP alpharecSEXP,SEXP lambdarecSEXP,SEXP betarecSEXP,
SEXP xplotSEXP, SEXP tplotSEXP, SEXP alphaSEXP) {
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type tplot(tplotSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xplot(xplotSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type alpharec(alpharecSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lambdarec(lambdarecSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type betarec(betarecSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    __result = Rcpp::wrap(predreg(alpharec,lambdarec,betarec,xplot,tplot,alpha));
    return __result;
}
